var subspeciality = {
        "english": [
            {
                "label_en": "Critical care medicine",
                "label_de": "Intensivmedizin",
                "label_nl": "Critical care medicine",
                "label_rs": "Медицина критических состояний",
                "label_sp": "Critical care medicine",
                "label_pt": "Critical care medicine",
                "label_sw": "Dawa muhimu ya utunzaji",
                "label_ch": "重症监护医学",
                "label_fr": "Médecine des soins intensifs",
                "value": "Critical_care_medicine"
            },
            {
                "label_en": "Hospice and palliative care",
                "label_de": "Hospice and palliative care",
                "label_nl": "Hospice and palliative care",
                "label_rs": "Хоспис и паллиативная помощь",
                "label_sp": "Hospice and palliative care",
                "label_pt": "Hospice and palliative care",
                "label_sw": "Hospitali na huduma ya kupendeza",
                "label_ch": "临终关怀和姑息治疗",
                "label_fr": "Hospices et soins palliatifs",
                "value": "Hospice_and_palliative_care"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Pediatric anesthesiology",
                "label_de": "Pädiatrische Anästhesiologie",
                "label_nl": "Pediatric anesthesiology",
                "label_rs": "Детская анестезиология",
                "label_sp": "Pediatric anesthesiology",
                "label_pt": "Pediatric anesthesiology",
                "label_sw": "Anesthesiolojia ya watoto",
                "label_ch": "儿科麻醉学",
                "label_fr": "Anesthésiologie pédiatrique",
                "value": "Pediatric_anesthesiology"
            },
            {
                "label_en": "Sleep medicine",
                "label_de": "Schlafmedizin",
                "label_nl": "Sleep medicine",
                "label_rs": "Медицина сна",
                "label_sp": "Sleep medicine",
                "label_pt": "Sleep medicine",
                "label_sw": "Dawa ya kulala",
                "label_ch": "睡眠药",
                "label_fr": "Médecine du sommeil",
                "value": "Sleep_medicine"
            },
            {
                "label_en": "Dermatopathology",
                "label_de": "Dermatopathologie",
                "label_nl": "Dermatopathologie",
                "label_rs": "Дерматопатология",
                "label_sp": "Dermatopatología",
                "label_pt": "Dermatopatologia",
                "label_sw": "Utibabu wa ngozi",
                "label_ch": "皮肤病理学",
                "label_fr": "Dermatopathologie",
                "value": "Dermatopathology"
            },
            {
                "label_en": "Pediatric dermatology",
                "label_de": "Pädiatrische Dermatologie",
                "label_nl": "Pediatric dermatology",
                "label_rs": "Детская дерматология",
                "label_sp": "Pediatric dermatology",
                "label_pt": "Pediatric dermatology",
                "label_sw": "Utibabu wa ngozi ya watoto",
                "label_ch": "儿科皮肤科",
                "label_fr": "Dermatologie pédiatrique",
                "value": "Pediatric_dermatology"
            },
            {
                "label_en": "Procedural dermatology",
                "label_de": "Verfahrensdermatologie",
                "label_nl": "Procedural dermatology",
                "label_rs": "Процедурная дерматология",
                "label_sp": "Procedural dermatology",
                "label_pt": "Procedural dermatology",
                "label_sw": "Utabibu wa ngozi kiutaratibu",
                "label_ch": "程序性皮肤科",
                "label_fr": "Dermatologie procédurale",
                "value": "Procedural_dermatology"
            },
            {
                "label_en": "Abdominal radiology",
                "label_de": "Bauchradiologie",
                "label_nl": "Abdominal radiology",
                "label_rs": "Абдоминальная радиология",
                "label_sp": "Abdominal radiology",
                "label_pt": "Abdominal radiology",
                "label_sw": "Radiolojia ya tumbo",
                "label_ch": "腹部放射科",
                "label_fr": "Radiologie abdominale",
                "value": "Abdominal_radiology"
            },
            {
                "label_en": "Breast imaging",
                "label_de": "Brustbildgebung",
                "label_nl": "Breast imaging",
                "label_rs": "Лучевые исследования молочной железы",
                "label_sp": "Breast imaging",
                "label_pt": "Breast imaging",
                "label_sw": "Picha ya matiti",
                "label_ch": "乳房成像",
                "label_fr": "Imagerie mammaire",
                "value": "Breast_imaging"
            },
            {
                "label_en": "Cardiothoracic radiology",
                "label_de": "Kardiothorakale Radiologie",
                "label_nl": "Cardiothoracic radiology",
                "label_rs": "Кардиоторакальная радиология",
                "label_sp": "Cardiothoracic radiology",
                "label_pt": "Cardiothoracic radiology",
                "label_sw": "Radiolojia ya moyo",
                "label_ch": "心胸放射科",
                "label_fr": "Radiologie cardiothoracique",
                "value": "Cardiothoracic_radiology"
            },
            {
                "label_en": "Cardiovascular radiology",
                "label_de": "Herz-Kreislauf-Radiologie",
                "label_nl": "Cardiovascular radiology",
                "label_rs": "Сердечно-сосудистая Радиология",
                "label_sp": "Cardiovascular radiology",
                "label_pt": "Cardiovascular radiology",
                "label_sw": "Radiolojia ya mishipa wa moyo",
                "label_ch": "心血管放射学",
                "label_fr": "Radiologie cardiovasculaire",
                "value": "Cardiovascular_radiology"
            },
            {
                "label_en": "Chest radiology",
                "label_de": "Brustradiologie",
                "label_nl": "Chest radiology",
                "label_rs": "Радиология грудной клетки",
                "label_sp": "Chest radiology",
                "label_pt": "Chest radiology",
                "label_sw": "Radiolojia ya kifua",
                "label_ch": "胸部放射科",
                "label_fr": "Radiologie thoracique",
                "value": "Chest_radiology"
            },
            {
                "label_en": "Emergency radiology",
                "label_de": "Notfallradiologie",
                "label_nl": "Emergency radiology",
                "label_rs": "Экстренная радиология",
                "label_sp": "Emergency radiology",
                "label_pt": "Emergency radiology",
                "label_sw": "Radiolojia ya dharura",
                "label_ch": "紧急放射科",
                "label_fr": "Radiologie d'urgence",
                "value": "Emergency_radiology"
            },
            {
                "label_en": "Endovascular surgical neuroradiology",
                "label_de": "Endovaskuläre chirurgische Neuroradiologie",
                "label_nl": "Endovascular surgical neuroradiology",
                "label_rs": "Эндоваскулярная хирургическая нейрорадиология",
                "label_sp": "Endovascular surgical neuroradiology",
                "label_pt": "Endovascular surgical neuroradiology",
                "label_sw": "Neuroradiolojia ya upasuaji wa mishipa",
                "label_ch": "血管内手术神经放射学",
                "label_fr": "Neuroradiologie chirurgicale endovasculaire",
                "value": "Endovascular_surgical_neuroradiology"
            },
            {
                "label_en": "Gastrointestinal radiology",
                "label_de": "Gastrointestinale Radiologie",
                "label_nl": "Gastrointestinal radiology",
                "label_rs": "Радиология желудочно-кишечного тракта",
                "label_sp": "Gastrointestinal radiology",
                "label_pt": "Gastrointestinal radiology",
                "label_sw": "Radiolojia ya njia ya utumbo",
                "label_ch": "胃肠放射科",
                "label_fr": "Radiologie gastro-intestinale",
                "value": "Gastrointestinal_radiology"
            },
            {
                "label_en": "Genitourinary radiology",
                "label_de": "Urogenitale Radiologie",
                "label_nl": "Genitourinary radiology",
                "label_rs": "Радиология мочеполовой системы",
                "label_sp": "Genitourinary radiology",
                "label_pt": "Genitourinary radiology",
                "label_sw": "Radiolojia ya mionzi ya kizazi",
                "label_ch": "泌尿生殖放射科",
                "label_fr": "Radiologie génito-urinaire",
                "value": "Genitourinary_radiology"
            },
            {
                "label_en": "Head and neck radiology",
                "label_de": "Kopf-und Halsradiologie",
                "label_nl": "Head and neck radiology",
                "label_rs": "Радиология головы и шеи",
                "label_sp": "Head and neck radiology",
                "label_pt": "Head and neck radiology",
                "label_sw": "Radiolojia ya kichwa na shingo",
                "label_ch": "头颈部放射科",
                "label_fr": "Radiologie de la tête et du cou",
                "value": "Head_and_neck_radiology"
            },
            {
                "label_en": "Interventional radiology",
                "label_de": "Interventionellen Radiologie",
                "label_nl": "Interventional radiology",
                "label_rs": "Инвазивная радиология",
                "label_sp": "Interventional radiology",
                "label_pt": "Interventional radiology",
                "label_sw": "Radiolojia ya kuingilia kati",
                "label_ch": "介入放射学",
                "label_fr": "Radiologie interventionnelle",
                "value": "Interventional_radiology"
            },
            {
                "label_en": "Musculoskeletal radiology",
                "label_de": "Radiologie des Bewegungsapparates",
                "label_nl": "Musculoskeletal radiology",
                "label_rs": "Радиология опорно-двигательного аппарата",
                "label_sp": "Musculoskeletal radiology",
                "label_pt": "Musculoskeletal radiology",
                "label_sw": "Radiolojia ya misuli",
                "label_ch": "肌肉骨骼放射学",
                "label_fr": "Radiologie musculo-squelettique",
                "value": "Musculoskeletal_radiology"
            },
            {
                "label_en": "Neuroradiology",
                "label_de": "Neuroradiologie",
                "label_nl": "Neuroradiologie",
                "label_rs": "Нейрорадиология",
                "label_sp": "Neurorradiología",
                "label_pt": "Neurorradiologia",
                "label_sw": "Neuroradiolojia",
                "label_ch": "神经放射学",
                "label_fr": "Neuroradiologie",
                "value": "Neuroradiology"
            },
            {
                "label_en": "Nuclear radiology",
                "label_de": "Nukleare Radiologie",
                "label_nl": "Nuclear radiology",
                "label_rs": "Ядерная радиология",
                "label_sp": "Nuclear radiology",
                "label_pt": "Nuclear radiology",
                "label_ch": "核放射学",
                "label_fr": "Radiologie nucléaire",
                "value": "Nuclear_radiology"
            },
            {
                "label_en": "Pediatric radiology",
                "label_de": "Pädiatrische Radiologie",
                "label_nl": "Pediatric radiology",
                "label_rs": "Детская радиология",
                "label_sp": "Pediatric radiology",
                "label_pt": "Pediatric radiology",
                "label_sw": "Radiolojia ya watoto",
                "label_ch": "儿科放射科",
                "label_fr": "Radiologie pédiatrique",
                "value": "Pediatric_radiology"
            },
            {
                "label_en": "Radiation oncology",
                "label_de": "Radioonkologie",
                "label_nl": "Radiation oncology",
                "label_rs": "Радиационная онкология",
                "label_sp": "Radiation oncology",
                "label_pt": "Radiation oncology",
                "label_sw": "Oncolojia ya mionzi",
                "label_ch": "放射肿瘤学",
                "label_fr": "Radio-oncologie",
                "value": "Radiation_oncology"
            },
            {
                "label_en": "Vascular and interventional radiology",
                "label_de": "Gefäß-und interventionelle Radiologie",
                "label_nl": "Vascular and interventional radiology",
                "label_rs": "Сосудистая и интервенционная радиология",
                "label_sp": "Vascular and interventional radiology",
                "label_pt": "Vascular and interventional radiology",
                "label_sw": "Radiolojia ya mishipa na ya kuingilia kati",
                "label_ch": "血管和介入放射学",
                "label_fr": "Radiologie vasculaire et interventionnelle",
                "value": "Vascular_and_interventional_radiology"
            },
            {
                "label_en": "Anesthesiology critical care medicine",
                "label_de": "Anästhesiologische Intensivmedizin",
                "label_nl": "Anesthesiology critical care medicine",
                "label_rs": "Анестезиология реаниматология",
                "label_sp": "Anesthesiology critical care medicine",
                "label_pt": "Anesthesiology critical care medicine",
                "label_sw": "Dawa ya utunzaji muhimu ya Anesthesiolojia",
                "label_ch": "麻醉学重症监护医学",
                "label_fr": "Anesthésiologie médecine de soins intensifs",
                "value": "Anesthesiology_critical_care_medicine"
            },
            {
                "label_en": "Emergency medical services",
                "label_de": "Notfallmedizin",
                "label_nl": "Emergency medical services",
                "label_rs": "Скорая медицинская помощь",
                "label_sp": "Emergency medical services",
                "label_pt": "Emergency medical services",
                "label_sw": "Huduma za dharura za matibabu",
                "label_ch": "紧急医疗服务",
                "label_fr": "Services médicaux d'urgence",
                "value": "Emergency_medical_services"
            },
            {
                "label_en": "Hospice and palliative medicine",
                "label_de": "Hospiz und Palliativmedizin",
                "label_nl": "Hospice and palliative medicine",
                "label_rs": "Хоспис и паллиативная медицина",
                "label_sp": "Hospice and palliative medicine",
                "label_pt": "Hospice and palliative medicine",
                "label_sw": "Hospitali na dawa ya kutuliza",
                "label_ch": "临终关怀和姑息药",
                "label_fr": "Hospice et médecine palliative",
                "value": "Hospice_and_palliative_medicine"
            },
            {
                "label_en": "Internal medicine / Critical care medicine",
                "label_de": "Innere Medizin / Intensivmedizin",
                "label_nl": "Internal medicine / Critical care medicine",
                "label_rs": "Внутренняя медицина/медицина критических состояний",
                "label_sp": "Internal medicine / Critical care medicine",
                "label_pt": "Internal medicine / Critical care medicine",
                "label_sw": "Dawa ya undani / Dawa muhimu ya utunzaji",
                "label_ch": "内科/重症医学",
                "label_fr": "Médecine interne / Médecine des soins intensifs",
                "value": "Internal_medicine_/_Critical_care_medicine"
            },
            {
                "label_en": "Medical toxicology",
                "label_de": "Medizinische Toxikologie",
                "label_nl": "Medical toxicology",
                "label_rs": "Медицинская токсикология",
                "label_sp": "Medical toxicology",
                "label_pt": "Medical toxicology",
                "label_sw": "Matibabu ya sumu",
                "label_ch": "医学毒理学",
                "label_fr": "Toxicologie médicale",
                "value": "Medical_toxicology"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Pediatric emergency medicine",
                "label_de": "Pädiatrische Notfallmedizin",
                "label_nl": "Pediatric emergency medicine",
                "label_rs": "Педиатрическая неотложная медицина",
                "label_sp": "Pediatric emergency medicine",
                "label_pt": "Pediatric emergency medicine",
                "label_sw": "Dawa ya dharura ya watoto",
                "label_ch": "儿科急诊医学",
                "label_fr": "Médecine d'urgence pédiatrique",
                "value": "Pediatric_emergency_medicine"
            },
            {
                "label_en": "Sports medicine",
                "label_de": "Sportmedizin",
                "label_nl": "Sports medicine",
                "label_rs": "Спортивная медицина",
                "label_sp": "Sports medicine",
                "label_pt": "Sports medicine",
                "label_sw": "Dawa ya michezo",
                "label_ch": "运动医学",
                "label_fr": "Médecine du sport",
                "value": "Sports_medicine"
            },
            {
                "label_en": "Undersea and hyperbaric medicine",
                "label_de": "Unterwasser-und Überdruckmedizin",
                "label_nl": "Undersea and hyperbaric medicine",
                "label_rs": "Подводная и гипербарическая медицина",
                "label_sp": "Undersea and hyperbaric medicine",
                "label_pt": "Undersea and hyperbaric medicine",
                "label_sw": "Dawa ya chini ya maji na hyperbaric",
                "label_ch": "海底和高压医学",
                "label_fr": "Médecine sous-marine et hyperbare",
                "value": "Undersea_and_hyperbaric_medicine"
            },
            {
                "label_en": "Adolescent medicine",
                "label_de": "Jugendmedizin",
                "label_nl": "Adolescent medicine",
                "label_rs": "Подростковая медицина",
                "label_sp": "Adolescent medicine",
                "label_pt": "Adolescent medicine",
                "label_sw": "Dawa ya vijana",
                "label_ch": "青少年医学",
                "label_fr": "Médecine des adolescents",
                "value": "Adolescent_medicine"
            },
            {
                "label_en": "Geriatric medicine",
                "label_de": "Geriatrie",
                "label_nl": "Geriatric medicine",
                "label_rs": "Гериатрическая медицина",
                "label_sp": "Geriatric medicine",
                "label_pt": "Geriatric medicine",
                "label_sw": "Dawa ya Geriatric",
                "label_ch": "老年医学",
                "label_fr": "Médecine gériatrique",
                "value": "Geriatric_medicine"
            },
            {
                "label_en": "Hospice and palliative medicine",
                "label_de": "Hospiz und Palliativmedizin",
                "label_nl": "Hospice and palliative medicine",
                "label_rs": "Хоспис и паллиативная медицина",
                "label_sp": "Hospice and palliative medicine",
                "label_pt": "Hospice and palliative medicine",
                "label_sw": "Hospitali na dawa ya kutuliza",
                "label_ch": "临终关怀和姑息药",
                "label_fr": "Hospice et médecine palliative",
                "value": "Hospice_and_palliative_medicine"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Sleep medicine",
                "label_de": "Schlafmedizin",
                "label_nl": "Sleep medicine",
                "label_rs": "Медицина сна",
                "label_sp": "Sleep medicine",
                "label_pt": "Sleep medicine",
                "label_sw": "Dawa ya kulala",
                "label_ch": "睡眠药",
                "label_fr": "Médecine du sommeil",
                "value": "Sleep_medicine"
            },
            {
                "label_en": "Sports medicine",
                "label_de": "Sportmedizin",
                "label_nl": "Sports medicine",
                "label_rs": "Спортивная медицина",
                "label_sp": "Sports medicine",
                "label_pt": "Sports medicine",
                "label_sw": "Dawa ya michezo",
                "label_ch": "运动医学",
                "label_fr": "Médecine du sport",
                "value": "Sports_medicine"
            },
            {
                "label_en": "Advanced heart failure and transplant cardiology",
                "label_de": "Fortgeschrittene Herzinsuffizienz und Transplantationskardiologie",
                "label_nl": "Advanced heart failure and transplant cardiology",
                "label_rs": "Сердечная недостаточность и трансплантационная кардиология",
                "label_sp": "Advanced heart failure and transplant cardiology",
                "label_pt": "Advanced heart failure and transplant cardiology",
                "label_sw": "Kushindwa kwa moyo wa hali ya juu na kupandikiza moyo",
                "label_ch": "高级心力衰竭和移植心脏病学",
                "label_fr": "Insuffisance cardiaque avancée et cardiologie de la transplantation",
                "value": "Advanced_heart_failure_and_transplant_cardiology"
            },
            {
                "label_en": "Cardiovascular disease",
                "label_de": "Kardiologie",
                "label_nl": "Cardiovascular disease",
                "label_rs": "Сердечно-сосудистые заболевания",
                "label_sp": "Cardiovascular disease",
                "label_pt": "Cardiovascular disease",
                "label_sw": "Ugonjwa wa moyo na mishipa",
                "label_ch": "心血管疾病",
                "label_fr": "Maladies cardiovasculaires",
                "value": "Cardiovascular_disease"
            },
            {
                "label_en": "Clinical cardiac electrophysiology",
                "label_de": "Angiologie",
                "label_nl": "Clinical cardiac electrophysiology",
                "label_rs": "Клиническая электрофизиологииясердца",
                "label_sp": "Clinical cardiac electrophysiology",
                "label_pt": "Clinical cardiac electrophysiology",
                "label_sw": "Kliniki ya elektroniki ya moyo",
                "label_ch": "临床心脏电生理",
                "label_fr": "Électrophysiologie cardiaque clinique",
                "value": "Clinical_cardiac_electrophysiology"
            },
            {
                "label_en": "Critical care medicine",
                "label_de": "Intensivmedizin",
                "label_nl": "Critical care medicine",
                "label_rs": "Медицина критических состояний",
                "label_sp": "Critical care medicine",
                "label_pt": "Critical care medicine",
                "label_sw": "Dawa muhimu ya utunzaji",
                "label_ch": "重症监护医学",
                "label_fr": "Médecine des soins intensifs",
                "value": "Critical_care_medicine"
            },
            {
                "label_en": "Endocrinology, diabetes, and metabolism",
                "label_de": "Endokrinologie, Diabetes und Stoffwechsel",
                "label_nl": "Endocrinology, diabetes, and metabolism",
                "label_rs": "Эндокринология, диабет и обмен веществ",
                "label_sp": "Endocrinology, diabetes, and metabolism",
                "label_pt": "Endocrinology, diabetes, and metabolism",
                "label_sw": "Endocrinolojia, ugonjwa wa sukari na kimetaboliki",
                "label_ch": "内分泌、糖尿病和代谢",
                "label_fr": "Endocrinologie, diabète et métabolisme",
                "value": "Endocrinology,_diabetes,_and_metabolism"
            },
            {
                "label_en": "Gastroenterology",
                "label_de": "Gastroenterologie",
                "label_nl": "Gastroenterologie",
                "label_rs": "Гастроэнтерология",
                "label_sp": "Gastroenterología",
                "label_pt": "Gastroenterologia",
                "label_sw": "Ugonjwa wa tumbo",
                "label_ch": "胃肠病学",
                "label_fr": "Gastroentérologie",
                "value": "Gastroenterology"
            },
            {
                "label_en": "Geriatric medicine",
                "label_de": "Geriatrie",
                "label_nl": "Geriatric medicine",
                "label_rs": "Гериатрическая медицина",
                "label_sp": "Geriatric medicine",
                "label_pt": "Geriatric medicine",
                "label_sw": "Dawa ya Geriatric",
                "label_ch": "老年医学",
                "label_fr": "Médecine gériatrique",
                "value": "Geriatric_medicine"
            },
            {
                "label_en": "Hematology",
                "label_de": "Hämatologie",
                "label_nl": "Hematologie",
                "label_rs": "Гематология",
                "label_sp": "Hematología",
                "label_pt": "Hematologia",
                "label_sw": "Hematolojia",
                "label_ch": "血液学",
                "label_fr": "Hématologie",
                "value": "Hematology"
            },
            {
                "label_en": "Hematology and oncology",
                "label_de": "Hämatologie und Onkologie",
                "label_nl": "Hematology and oncology",
                "label_rs": "Гематология и онкология",
                "label_sp": "Hematology and oncology",
                "label_pt": "Hematology and oncology",
                "label_sw": "Hematolojia na oncolojia",
                "label_ch": "血液学和肿瘤学",
                "label_fr": "Hématologie et oncologie",
                "value": "Hematology_and_oncology"
            },
            {
                "label_en": "Infectious disease",
                "label_de": "Infektiologie",
                "label_nl": "Infectious disease",
                "label_rs": "Инфекционное заболевание",
                "label_sp": "Infectious disease",
                "label_pt": "Infectious disease",
                "label_sw": "Ugonjwa wa kuambukiza",
                "label_ch": "传染病",
                "label_fr": "Maladies infectieuses",
                "value": "Infectious_disease"
            },
            {
                "label_en": "Internal medicine",
                "label_de": "Innere Medizin",
                "label_nl": "Internal medicine",
                "label_rs": "ВНУТРЕННЯЯ МЕДИЦИНА",
                "label_sp": "Internal medicine",
                "label_pt": "Internal medicine",
                "label_sw": "Dawa ya undani",
                "label_ch": "内科",
                "label_fr": "Internal medicine",
                "value": "Internal_medicine"
            },
            {
                "label_en": "Interventional cardiology",
                "label_de": "Interventionelle Kardiologie",
                "label_nl": "Interventional cardiology",
                "label_rs": "Инвазивная кардиология",
                "label_sp": "Interventional cardiology",
                "label_pt": "Interventional cardiology",
                "label_sw": "Cardiolojia ya kuingilia kati",
                "label_ch": "介入心脏病学",
                "label_fr": "Cardiologie interventionnelle",
                "value": "Interventional_cardiology"
            },
            {
                "label_en": "Nephrology",
                "label_de": "Nephrologie",
                "label_nl": "Nefrologie",
                "label_rs": "Нефрология",
                "label_sp": "Nefrología",
                "label_pt": "Nefrologia",
                "label_sw": "Nephrolojia",
                "label_ch": "肾脏病",
                "label_fr": "Néphrologie",
                "value": "Nephrology"
            },
            {
                "label_en": "Oncology",
                "label_de": "Onkologie",
                "label_nl": "Oncologie",
                "label_rs": "ОНКОЛОГИЯ",
                "label_sp": "Oncología",
                "label_pt": "Oncologia",
                "label_sw": "Oncolojia",
                "label_ch": "肿瘤学",
                "label_fr": "Oncologie",
                "value": "Oncology"
            },
            {
                "label_en": "Pediatric internal medicine",
                "label_de": "Pädiatrische Innere Medizin",
                "label_nl": "Pediatric internal medicine",
                "label_rs": "Педиатрическая внутренняя медицина",
                "label_sp": "Pediatric internal medicine",
                "label_pt": "Pediatric internal medicine",
                "label_sw": "Dawa ya ndani ya watoto",
                "label_ch": "小儿内科",
                "label_fr": "Médecine interne pédiatrique",
                "value": "Pediatric_internal_medicine"
            },
            {
                "label_en": "Pulmonary disease",
                "label_de": "Pulmonary disease",
                "label_nl": "Pulmonary disease",
                "label_rs": "Легочная болезнь",
                "label_sp": "Pulmonary disease",
                "label_pt": "Pulmonary disease",
                "label_sw": "Ugonjwa wa mapafu",
                "label_ch": "肺部疾病",
                "label_fr": "Maladie pulmonaire",
                "value": "Pulmonary_disease"
            },
            {
                "label_en": "Pulmonary disease and critical care medicine",
                "label_de": "Pneumologie und Intensivmedizin",
                "label_nl": "Pulmonary disease and critical care medicine",
                "label_rs": "Легочные заболевания и медицина критических состояний",
                "label_sp": "Pulmonary disease and critical care medicine",
                "label_pt": "Pulmonary disease and critical care medicine",
                "label_sw": "Ugonjwa wa mapafu na dawa ya utunzaji muhimu",
                "label_ch": "肺病和重症监护医学",
                "label_fr": "Maladies pulmonaires et médecine des soins intensifs",
                "value": "Pulmonary_disease_and_critical_care_medicine"
            },
            {
                "label_en": "Rheumatology",
                "label_de": "Rheumatologie",
                "label_nl": "Reumatologie",
                "label_rs": "Ревматология",
                "label_sp": "Reumatología",
                "label_pt": "Reumatologia",
                "label_sw": "Rheumatolojia",
                "label_ch": "风湿病",
                "label_fr": "Rhumatologie",
                "value": "Rheumatology"
            },
            {
                "label_en": "Sleep medicine",
                "label_de": "Schlafmedizin",
                "label_nl": "Sleep medicine",
                "label_rs": "Медицина сна",
                "label_sp": "Sleep medicine",
                "label_pt": "Sleep medicine",
                "label_sw": "Dawa ya kulala",
                "label_ch": "睡眠药",
                "label_fr": "Médecine du sommeil",
                "value": "Sleep_medicine"
            },
            {
                "label_en": "Sports medicine",
                "label_de": "Sportmedizin",
                "label_nl": "Sports medicine",
                "label_rs": "Спортивная медицина",
                "label_sp": "Sports medicine",
                "label_pt": "Sports medicine",
                "label_sw": "Dawa ya michezo",
                "label_ch": "运动医学",
                "label_fr": "Médecine du sport",
                "value": "Sports_medicine"
            },
            {
                "label_en": "Transplant hepatology",
                "label_de": "Transplantationshepatologie",
                "label_nl": "Transplant hepatology",
                "label_rs": "Трансплантационная гепатология",
                "label_sp": "Transplant hepatology",
                "label_pt": "Transplant hepatology",
                "label_sw": "Kupandikiza hepatolojia",
                "label_ch": "移植肝病",
                "label_fr": "Hépatologie de la transplantation",
                "value": "Transplant_hepatology"
            },
            {
                "label_en": "Biochemical genetics",
                "label_de": "Biochemische Genetik",
                "label_nl": "Biochemical genetics",
                "label_rs": "Биохимическая генетика",
                "label_sp": "Biochemical genetics",
                "label_pt": "Biochemical genetics",
                "label_sw": "Maumbile ya biokemikali",
                "label_ch": "生化遗传学",
                "label_fr": "Génétique biochimique",
                "value": "Biochemical_genetics"
            },
            {
                "label_en": "Clinical cytogenetics",
                "label_de": "Klinische Zytogenetik",
                "label_nl": "Clinical cytogenetics",
                "label_rs": "Клиническая цитогенетика",
                "label_sp": "Clinical cytogenetics",
                "label_pt": "Clinical cytogenetics",
                "label_sw": "Kliniki ya cytogenetics",
                "label_ch": "临床细胞遗传学",
                "label_fr": "Cytogénétique clinique",
                "value": "Clinical_cytogenetics"
            },
            {
                "label_en": "Clinical genetics",
                "label_de": "Klinische Genetik",
                "label_nl": "Clinical genetics",
                "label_rs": "Клиническая генетика",
                "label_sp": "Clinical genetics",
                "label_pt": "Clinical genetics",
                "label_sw": "Kliniki ya maumbile",
                "label_ch": "临床遗传学",
                "label_fr": "Génétique clinique",
                "value": "Clinical_genetics"
            },
            {
                "label_en": "Molecular genetic pathology",
                "label_de": "Molekulargenetische Pathologie",
                "label_nl": "Molecular genetic pathology",
                "label_rs": "Молекулярно-генетическая патология",
                "label_sp": "Molecular genetic pathology",
                "label_pt": "Molecular genetic pathology",
                "label_sw": "Patholojia ya maumbile ya Masi",
                "label_ch": "分子遗传病理学",
                "label_fr": "Pathologie génétique moléculaire",
                "value": "Molecular_genetic_pathology"
            },
            {
                "label_en": "Brain injury medicine",
                "label_de": "Arzneimittel gegen Hirnverletzungen",
                "label_nl": "Brain injury medicine",
                "label_rs": "Медицина ЧМТ",
                "label_sp": "Brain injury medicine",
                "label_pt": "Brain injury medicine",
                "label_sw": "Dawa ya kuumia ubongo",
                "label_ch": "脑损伤医学",
                "label_fr": "Médecine des lésions cérébrales",
                "value": "Brain_injury_medicine"
            },
            {
                "label_en": "Child neurology",
                "label_de": "Kinderneurologie",
                "label_nl": "Child neurology",
                "label_rs": "Детская неврология",
                "label_sp": "Child neurology",
                "label_pt": "Child neurology",
                "label_sw": "Mishipa ya watoto",
                "label_ch": "儿童神经病学",
                "label_fr": "Neurologie de l'enfant",
                "value": "Child_neurology"
            },
            {
                "label_en": "Clinical neurophysiology",
                "label_de": "Klinische Neurophysiologie",
                "label_nl": "Clinical neurophysiology",
                "label_rs": "Клиническая нейрофизиология",
                "label_sp": "Clinical neurophysiology",
                "label_pt": "Clinical neurophysiology",
                "label_sw": "Kliniki_ ya neurophysiolojia",
                "label_ch": "临床神经生理学",
                "label_fr": "Neurophysiologie clinique",
                "value": "Clinical_neurophysiology"
            },
            {
                "label_en": "Endovascular surgical neuroradiology",
                "label_de": "Endovaskuläre chirurgische Neuroradiologie",
                "label_nl": "Endovascular surgical neuroradiology",
                "label_rs": "Эндоваскулярная хирургическая нейрорадиология",
                "label_sp": "Endovascular surgical neuroradiology",
                "label_pt": "Endovascular surgical neuroradiology",
                "label_sw": "Neuroradiolojia ya upasuaji wa mishipa",
                "label_ch": "血管内手术神经放射学",
                "label_fr": "Neuroradiologie chirurgicale endovasculaire",
                "value": "Endovascular_surgical_neuroradiology"
            },
            {
                "label_en": "Hospice and palliative medicine",
                "label_de": "Hospiz und Palliativmedizin",
                "label_nl": "Hospice and palliative medicine",
                "label_rs": "Хоспис и паллиативная медицина",
                "label_sp": "Hospice and palliative medicine",
                "label_pt": "Hospice and palliative medicine",
                "label_sw": "Hospitali na dawa ya kutuliza",
                "label_ch": "临终关怀和姑息药",
                "label_fr": "Hospice et médecine palliative",
                "value": "Hospice_and_palliative_medicine"
            },
            {
                "label_en": "Neurodevelopmental disabilities",
                "label_de": "Neuroentwicklungsstörungen",
                "label_nl": "Neurodevelopmental disabilities",
                "label_rs": "Нарушения нервно-психического развития",
                "label_sp": "Neurodevelopmental disabilities",
                "label_pt": "Neurodevelopmental disabilities",
                "label_sw": "Ulemavu wa maendeleo ya neva",
                "label_ch": "神经发育障碍",
                "label_fr": "Troubles neurologiques du développement",
                "value": "Neurodevelopmental_disabilities"
            },
            {
                "label_en": "Neuromuscular medicine",
                "label_de": "Neuromuskuläre Medizin",
                "label_nl": "Neuromuscular medicine",
                "label_rs": "Нервно-мышечная медицина",
                "label_sp": "Neuromuscular medicine",
                "label_pt": "Neuromuscular medicine",
                "label_sw": "Dawa ya mshipa wa neva",
                "label_ch": "神经肌肉医学",
                "label_fr": "Médecine neuromusculaire",
                "value": "Neuromuscular_medicine"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Sleep medicine",
                "label_de": "Schlafmedizin",
                "label_nl": "Sleep medicine",
                "label_rs": "Медицина сна",
                "label_sp": "Sleep medicine",
                "label_pt": "Sleep medicine",
                "label_sw": "Dawa ya kulala",
                "label_ch": "睡眠药",
                "label_fr": "Médecine du sommeil",
                "value": "Sleep_medicine"
            },
            {
                "label_en": "Vascular neurology",
                "label_de": "Gefäßneurologie",
                "label_nl": "Vascular neurology",
                "label_rs": "Сосудистая неврология",
                "label_sp": "Vascular neurology",
                "label_pt": "Vascular neurology",
                "label_sw": "Mishipa ya fahamu",
                "label_ch": "血管神经学",
                "label_fr": "Neurologie vasculaire",
                "value": "Vascular_neurology"
            },
            {
                "label_en": "Female pelvic medicine and reconstructive surgery",
                "label_de": "Weibliche Beckenmedizin und rekonstruktive Chirurgie",
                "label_nl": "Female pelvic medicine and reconstructive surgery",
                "label_rs": "Женская тазовая медицина и реконструктивная хирургия",
                "label_sp": "Female pelvic medicine and reconstructive surgery",
                "label_pt": "Female pelvic medicine and reconstructive surgery",
                "label_sw": "Dawa ya kiuno ya kike na upasuaji wa ujenzi",
                "label_ch": "女性骨盆医学和重建手术",
                "label_fr": "Médecine pelvienne féminine et chirurgie reconstructive",
                "value": "Female_pelvic_medicine_and_reconstructive_surgery"
            },
            {
                "label_en": "Gynecologic oncology",
                "label_de": "Gynäkologische Onkologie",
                "label_nl": "Gynecologic oncology",
                "label_rs": "Гинекологическая онкология",
                "label_sp": "Gynecologic oncology",
                "label_pt": "Gynecologic oncology",
                "label_sw": "Oncolojia ya Gynecologic",
                "label_ch": "妇科肿瘤",
                "label_fr": "Oncologie gynécologique",
                "value": "Gynecologic_oncology"
            },
            {
                "label_en": "Maternal-fetal medicine",
                "label_de": "Mütterlich-fetale Medizin",
                "label_nl": "Maternal-fetal medicine",
                "label_rs": "Материнско-фетальная медицина",
                "label_sp": "Maternal-fetal medicine",
                "label_pt": "Maternal-fetal medicine",
                "label_sw": "Dawa ya fetasi ya mama",
                "label_ch": "母胎医学",
                "label_fr": "Médecine materno-fœtale",
                "value": "Maternal-fetal_medicine"
            },
            {
                "label_en": "Reproductive endocrinologists and infertility",
                "label_de": "Fortpflanzungsendokrinologie und Unfruchtbarkeit",
                "label_nl": "Reproductive endocrinologists and infertility",
                "label_rs": "Репродуктивная эндокринология и бесплодие",
                "label_sp": "Reproductive endocrinologists and infertility",
                "label_pt": "Reproductive endocrinologists and infertility",
                "label_sw": "Wataalam wa endocrinolojia ya uzazi na utasa",
                "label_ch": "生殖内分泌学和不孕不育",
                "label_fr": "Endocrinologues de la reproduction et infertilité",
                "value": "Reproductive_endocrinologists_and_infertility"
            },
            {
                "label_en": "Anterior segment/cornea ophthalmology",
                "label_de": "Ophtalmologie des vorderen Augensegments / der Hornhaut",
                "label_nl": "Anterior segment/cornea ophthalmology",
                "label_rs": "Офтальмология роговицы",
                "label_sp": "Anterior segment/cornea ophthalmology",
                "label_pt": "Anterior segment/cornea ophthalmology",
                "label_sw": "Sehemu ya mbele / ophthalmolojia ya koni",
                "label_ch": "前段/角膜眼科",
                "label_fr": "Segment antérieur/ophtalmologie de la cornée",
                "value": "Anterior_segment/cornea_ophthalmology"
            },
            {
                "label_en": "Glaucoma ophthalmology",
                "label_de": "Glaukom-Augenheilkunde",
                "label_nl": "Glaucoma ophthalmology",
                "label_rs": "Офтальмология глаукомы",
                "label_sp": "Glaucoma ophthalmology",
                "label_pt": "Glaucoma ophthalmology",
                "label_sw": "Glaucoma ophthalmolojia",
                "label_ch": "青光眼眼科",
                "label_fr": "Ophtalmologie du glaucome",
                "value": "Glaucoma_ophthalmology"
            },
            {
                "label_en": "Neuro-ophthalmology",
                "label_de": "Neuro-Ophthalmologie",
                "label_nl": "Neuro-oogkunde",
                "label_rs": "Нейроофтальмология",
                "label_sp": "Neurooftalmología",
                "label_pt": "Neurooftalmologia",
                "label_sw": "Neuro-ophthalmolojia",
                "label_ch": "眼肿瘤学",
                "label_fr": "Neuro-ophtalmologie",
                "value": "Neuro-ophthalmology"
            },
            {
                "label_en": "Ocular oncology",
                "label_de": "Augenonkologie",
                "label_nl": "Ocular oncology",
                "label_rs": "Глазная онкология",
                "label_sp": "Ocular oncology",
                "label_pt": "Ocular oncology",
                "label_sw": "Oncolojia ya macho",
                "label_ch": "神经眼科",
                "label_fr": "Oncologie oculaire",
                "value": "Ocular_oncology"
            },
            {
                "label_en": "Oculoplastics/orbit",
                "label_de": "Okuloplastik / Orbitaplastik",
                "label_nl": "Plastische chirurgie voor oogomgeving",
                "label_rs": "Окулопластика/орбиты",
                "label_sp": "Oculoplastia y Órbita",
                "label_pt": "Oculoplastia e Órbita",
                "label_sw": "Oculoplastics / obiti",
                "label_ch": "ﾂ环板篠ｮﾂ嘉ｯﾂ偲",
                "label_fr": "Oculoplastique / orbite",
                "value": "Oculoplastics/orbit"
            },
            {
                "label_en": "Ophthalmic Plastic & Reconstructive Surgery",
                "label_de": "Ophthalmologische plastische und rekonstruktive Chirurgie",
                "label_nl": "Ophthalmic Plastic & Reconstructive Surgery",
                "label_rs": "Офтальмологическая пластическая и реконструктивная хирургия",
                "label_sp": "Ophthalmic Plastic & Reconstructive Surgery",
                "label_pt": "Ophthalmic Plastic & Reconstructive Surgery",
                "label_sw": "Upasuaji wa Plastiki na Urekebishaji wa Ophthalmic",
                "label_ch": "眼科整形外科",
                "label_fr": "Chirurgie plastique et reconstructive ophtalmique",
                "value": "Ophthalmic_Plastic_&_Reconstructive_Surgery"
            },
            {
                "label_en": "Retina/uveitis",
                "label_de": "Netzhaut / Uveitis",
                "label_nl": "Retina/uveitis",
                "label_rs": "Сетчатка/увеит",
                "label_sp": "Retina/Uveítis",
                "label_pt": "Retina/Uveíte",
                "label_sw": "Retina / uveitis",
                "label_ch": "视网膜/葡萄膜炎",
                "label_fr": "Rétine / uvéite",
                "value": "Retina/uveitis"
            },
            {
                "label_en": "Strabismus/pediatric ophthalmology",
                "label_de": "Strabismus / Kinderaugenheilkunde",
                "label_nl": "Strabismus/pediatric ophthalmology",
                "label_rs": "Косоглазие/детская офтальмология",
                "label_sp": "Strabismus/pediatric ophthalmology",
                "label_pt": "Strabismus/pediatric ophthalmology",
                "label_sw": "Strabismus / ophthalmolojia ya watoto",
                "label_ch": "斜视/儿科眼科",
                "label_fr": "Strabisme/ophtalmologie pédiatrique",
                "value": "Strabismus/pediatric_ophthalmology"
            },
            {
                "label_en": "Blood banking and transfusion medicine",
                "label_de": "Blutbank- und Transfusionsmedizin",
                "label_nl": "Blood banking and transfusion medicine",
                "label_rs": "Заготовка крофи и трансфузионная медицина",
                "label_sp": "Blood banking and transfusion medicine",
                "label_pt": "Blood banking and transfusion medicine",
                "label_sw": "Benki ya damu na dawa ya kuongezea damu",
                "label_ch": "血库和输血医学",
                "label_fr": "Banque de sang et médecine transfusionnelle",
                "value": "Blood_banking_and_transfusion_medicine"
            },
            {
                "label_en": "Chemical pathology",
                "label_de": "Anatomische Pathologie",
                "label_nl": "Chemical pathology",
                "label_rs": "Химическая патология",
                "label_sp": "Chemical pathology",
                "label_pt": "Chemical pathology",
                "label_sw": "Ugonjwa wa kemikali",
                "label_ch": "化学病理学",
                "label_fr": "Pathologie chimique",
                "value": "Chemical_pathology"
            },
            {
                "label_en": "Cytopathology",
                "label_de": "Zytopathologie",
                "label_nl": "Cytopathologie",
                "label_rs": "Цитопатология",
                "label_sp": "Citopatología",
                "label_pt": "Citopatologia",
                "label_sw": "Cytopatholojia",
                "label_ch": "细胞病理学",
                "label_fr": "Cytopathologie",
                "value": "Cytopathology"
            },
            {
                "label_en": "Forensic pathology",
                "label_de": "Forensische Pathologie",
                "label_nl": "Forensic pathology",
                "label_rs": "Судебная патология",
                "label_sp": "Forensic pathology",
                "label_pt": "Forensic pathology",
                "label_sw": "Kuchunguza mauaji ya ugonjwa",
                "label_ch": "法医病理学",
                "label_fr": "Pathologie médico-légale",
                "value": "Forensic_pathology"
            },
            {
                "label_en": "Genetic pathology",
                "label_de": "Genetische Pathologie",
                "label_nl": "Genetic pathology",
                "label_rs": "Генетическая патология",
                "label_sp": "Genetic pathology",
                "label_pt": "Genetic pathology",
                "label_sw": "Ugonjwa wa maumbile",
                "label_ch": "遗传病理学",
                "label_fr": "Pathologie génétique",
                "value": "Genetic_pathology"
            },
            {
                "label_en": "Hematology",
                "label_de": "Hämatologie",
                "label_nl": "Hematologie",
                "label_rs": "Гематология",
                "label_sp": "Hematología",
                "label_pt": "Hematologia",
                "label_sw": "Hematolojia",
                "label_ch": "血液学",
                "label_fr": "Hématologie",
                "value": "Hematology"
            },
            {
                "label_en": "Immunopathology",
                "label_de": "Immunpathologie",
                "label_nl": "Immunopathologie",
                "label_rs": "Иммунопатология",
                "label_sp": "Inmunopatología",
                "label_pt": "Imunopatologia",
                "label_sw": "Immunopatholojia",
                "label_ch": "免疫病理学",
                "label_fr": "Immunopathologie",
                "value": "Immunopathology"
            },
            {
                "label_en": "Medical microbiology",
                "label_de": "Medizinische Mikrobiologie",
                "label_nl": "Medical microbiology",
                "label_rs": "Медицинская микробиология",
                "label_sp": "Medical microbiology",
                "label_pt": "Medical microbiology",
                "label_sw": "Matibabu ya microbiolojia",
                "label_ch": "医学微生物学",
                "label_fr": "Microbiologie médicale",
                "value": "Medical_microbiology"
            },
            {
                "label_en": "Molecular pathology",
                "label_de": "Molekulare Pathologie",
                "label_nl": "Molecular_pathology",
                "label_rs": "Молекулярная патология",
                "label_sp": "Molecular pathology",
                "label_pt": "Molecular pathology",
                "label_sw": "ugonjwa wa Masi",
                "label_ch": "分子病理学",
                "label_fr": "Pathologie moléculaire",
                "value": "Molecular_pathology"
            },
            {
                "label_en": "Neuropathology",
                "label_de": "Neuropathologie",
                "label_nl": "Neuropathologie",
                "label_rs": "Невропатология",
                "label_sp": "Neuropatología",
                "label_pt": "Neuropatologia",
                "label_sw": "Neuropatholojia",
                "label_ch": "神经病理学",
                "label_fr": "Neuropathologie",
                "value": "Neuropathology"
            },
            {
                "label_en": "Pediatric pathology",
                "label_de": "Pädiatrische Pathologie",
                "label_nl": "Pediatric pathology",
                "label_rs": "Детская патология",
                "label_sp": "Pediatric pathology",
                "label_pt": "Pediatric pathology",
                "label_sw": "ugonjwa wa watoto",
                "label_ch": "儿科病理",
                "label_fr": "Pathologie pédiatrique",
                "value": "Pediatric_pathology"
            },
            {
                "label_en": "Adolescent medicine",
                "label_de": "Jugendmedizin",
                "label_nl": "Adolescent medicine",
                "label_rs": "Подростковая медицина",
                "label_sp": "Adolescent medicine",
                "label_pt": "Adolescent medicine",
                "label_sw": "Dawa ya vijana",
                "label_ch": "青少年医学",
                "label_fr": "Médecine des adolescents",
                "value": "Adolescent_medicine"
            },
            {
                "label_en": "Child abuse pediatrics",
                "label_de": "Kindesmissbrauchsprävention",
                "label_nl": "Child abuse pediatrics",
                "label_rs": "Педиатрия жестокого обращения с детьми",
                "label_sp": "Child abuse pediatrics",
                "label_pt": "Child abuse pediatrics",
                "label_sw": "Matibabu ya watoto  wanaodhulumia",
                "label_ch": "儿童虐待儿科",
                "label_fr": "Pédiatrie des enfants maltraités",
                "value": "Child_abuse_pediatrics"
            },
            {
                "label_en": "Developmental-behavioral pediatrics",
                "label_de": "Entwicklungsverhaltenspädiatrie",
                "label_nl": "Developmental-behavioral pediatrics",
                "label_rs": "Развивающая и поведенческая педиатрия",
                "label_sp": "Developmental-behavioral pediatrics",
                "label_pt": "Developmental-behavioral pediatrics",
                "label_sw": "Watoto wa maendeleo kitabia",
                "label_ch": "发育行为儿科",
                "label_fr": "Pédiatrie développementale et comportementale",
                "value": "Developmental-behavioral_pediatrics"
            },
            {
                "label_en": "Neonatal-perinatal medicine",
                "label_de": "Medizin für Neugeborene und Perinatale",
                "label_nl": "Neonatal-perinatal medicine",
                "label_rs": "Неонатально-перинатальная медицина",
                "label_sp": "Neonatal-perinatal medicine",
                "label_pt": "Neonatal-perinatal medicine",
                "label_sw": "Dawa ya kuzaliwa kwa mtoto mchanga",
                "label_ch": "新生儿-围产期医学",
                "label_fr": "Médecine néonatale et périnatale",
                "value": "Neonatal-perinatal_medicine"
            },
            {
                "label_en": "Pediatric cardiology",
                "label_de": "Pädiatrische Kardiologie",
                "label_nl": "Pediatric cardiology",
                "label_rs": "Детская кардиология",
                "label_sp": "Pediatric cardiology",
                "label_pt": "Pediatric cardiology",
                "label_sw": "Ugonjwa wa moyo ya watoto",
                "label_ch": "儿科心脏病",
                "label_fr": "Cardiologie pédiatrique",
                "value": "Pediatric_cardiology"
            },
            {
                "label_en": "Pediatric critical care medicine",
                "label_de": "Pädiatrische Intensivmedizin",
                "label_nl": "Pediatric critical care medicine",
                "label_rs": "Медицина критических состояний в педиатрии",
                "label_sp": "Pediatric critical care medicine",
                "label_pt": "Pediatric critical care medicine",
                "label_sw": "Dawa ya utunzaji wa watoto muhimu",
                "label_ch": "儿科重症监护医学",
                "label_fr": "Médecine pédiatrique de soins intensifs",
                "value": "Pediatric_critical_care_medicine"
            },
            {
                "label_en": "Pediatric endocrinology",
                "label_de": "Pädiatrische Endokrinologie",
                "label_nl": "Pediatric endocrinology",
                "label_rs": "Детская эндокринология",
                "label_sp": "Pediatric endocrinology",
                "label_pt": "Pediatric endocrinology",
                "label_sw": "Endocrinolojia ya watoto",
                "label_ch": "儿科内分泌学",
                "label_fr": "Endocrinologie pédiatrique",
                "value": "Pediatric_endocrinology"
            },
            {
                "label_en": "Pediatric gastroenterology",
                "label_de": "Pädiatrische Gastroenterologie",
                "label_nl": "Pediatric gastroenterology",
                "label_rs": "Детская гастроэнтерология",
                "label_sp": "Pediatric gastroenterology",
                "label_pt": "Pediatric gastroenterology",
                "label_sw": "Gastroenterolojia ya watoto",
                "label_ch": "小儿胃肠病学",
                "label_fr": "Gastroentérologie pédiatrique",
                "value": "Pediatric_gastroenterology"
            },
            {
                "label_en": "Pediatric hematology-oncology",
                "label_de": "Pädiatrische Hämatologie-Onkologie",
                "label_nl": "Pediatric hematology-oncology",
                "label_rs": "Детская гематология-онкология",
                "label_sp": "Pediatric hematology-oncology",
                "label_pt": "Pediatric hematology-oncology",
                "label_sw": "hematology-oncolojia ya watoto",
                "label_ch": "小儿血液学-肿瘤学",
                "label_fr": "Hématologie-oncologie pédiatrique",
                "value": "Pediatric_hematology-oncology"
            },
            {
                "label_en": "Pediatric infectious diseases",
                "label_de": "Pädiatrische Infektionskrankheiten",
                "label_nl": "Pediatric infectious diseases",
                "label_rs": "Детские инфекционные заболевания",
                "label_sp": "Pediatric infectious diseases",
                "label_pt": "Pediatric infectious diseases",
                "label_sw": "Pediatric infectious diseases",
                "label_ch": "小儿传染病",
                "label_fr": "Maladies infectieuses pédiatriques",
                "value": "Pediatric_infectious_diseases"
            },
            {
                "label_en": "Pediatric nephrology",
                "label_de": "Pädiatrische Nephrologie",
                "label_nl": "Pediatric nephrology",
                "label_rs": "Детская нефрология",
                "label_sp": "Pediatric nephrology",
                "label_pt": "Pediatric nephrology",
                "label_sw": "Pediatric nephrology",
                "label_ch": "小儿肾病",
                "label_fr": "Néphrologie pédiatrique",
                "value": "Pediatric_nephrology"
            },
            {
                "label_en": "Pediatric pulmonology",
                "label_de": "Pädiatrische Pulmonologie",
                "label_nl": "Pediatric pulmonology",
                "label_rs": "Детская пульмонология",
                "label_sp": "Pediatric pulmonology",
                "label_pt": "Pediatric pulmonology",
                "label_sw": "Ugonjwa wa mapafu ya watoto",
                "label_ch": "小儿肺病",
                "label_fr": "Pneumologie pédiatrique",
                "value": "Pediatric_pulmonology"
            },
            {
                "label_en": "Pediatric rheumatology",
                "label_de": "Pädiatrische Rheumatologie",
                "label_nl": "Pediatric rheumatology",
                "label_rs": "Детская ревматология",
                "label_sp": "Pediatric rheumatology",
                "label_pt": "Pediatric rheumatology",
                "label_sw": "rheumatolojia ya watoto",
                "label_ch": "小儿风湿病",
                "label_fr": "Rhumatologie pédiatrique",
                "value": "Pediatric_rheumatology"
            },
            {
                "label_en": "Pediatric sports medicine",
                "label_de": "Pädiatrische Sportmedizin",
                "label_nl": "Pediatric sports medicine",
                "label_rs": "Детская спортивная медицина",
                "label_sp": "Pediatric sports medicine",
                "label_pt": "Pediatric sports medicine",
                "label_sw": "Dawa ya michezo ya watoto",
                "label_ch": "小儿运动医学",
                "label_fr": "Médecine sportive pédiatrique",
                "value": "Pediatric_sports_medicine"
            },
            {
                "label_en": "Pediatric transplant hepatology",
                "label_de": "Pädiatrische Transplantationshepatologie",
                "label_nl": "Pediatric transplant hepatology",
                "label_rs": "Детская трансплантационная гепатология",
                "label_sp": "Pediatric transplant hepatology",
                "label_pt": "Pediatric transplant hepatology",
                "label_sw": "hepatolojia ya kupandikiza watoto",
                "label_ch": "小儿移植肝病",
                "label_fr": "Hépatologie de la transplantation pédiatrique",
                "value": "Pediatric_transplant_hepatology"
            },
            {
                "label_en": "Brain injury medicine",
                "label_de": "Arzneimittel gegen Hirnverletzungen",
                "label_nl": "Brain injury medicine",
                "label_rs": "Медицина ЧМТ",
                "label_sp": "Brain injury medicine",
                "label_pt": "Brain injury medicine",
                "label_sw": "Dawa ya kuumia ubongo",
                "label_ch": "脑损伤医学",
                "label_fr": "Médecine des lésions cérébrales",
                "value": "Brain_injury_medicine"
            },
            {
                "label_en": "Hospice and palliative medicine",
                "label_de": "Hospiz und Palliativmedizin",
                "label_nl": "Hospice and palliative medicine",
                "label_rs": "Хоспис и паллиативная медицина",
                "label_sp": "Hospice and palliative medicine",
                "label_pt": "Hospice and palliative medicine",
                "label_sw": "Hospitali na dawa ya kutuliza",
                "label_ch": "临终关怀和姑息药",
                "label_fr": "Hospice et médecine palliative",
                "value": "Hospice_and_palliative_medicine"
            },
            {
                "label_en": "Neuromuscular medicine",
                "label_de": "Neuromuskuläre Medizin",
                "label_nl": "Neuromuscular medicine",
                "label_rs": "Нервно-мышечная медицина",
                "label_sp": "Neuromuscular medicine",
                "label_pt": "Neuromuscular medicine",
                "label_sw": "Dawa ya mshipa wa neva",
                "label_ch": "神经肌肉医学",
                "label_fr": "Médecine neuromusculaire",
                "value": "Neuromuscular_medicine"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Pediatric rehabilitation medicine",
                "label_de": "Pädiatrische Rehabilitationsmedizin",
                "label_nl": "Pediatric rehabilitation medicine",
                "label_rs": "Детская реабилитационная медицина",
                "label_sp": "Pediatric rehabilitation medicine",
                "label_pt": "Pediatric rehabilitation medicine",
                "label_sw": "Dawa ya ukarabati wa watoto",
                "label_ch": "小儿康复医学",
                "label_fr": "Médecine de réadaptation pédiatrique",
                "value": "Pediatric_rehabilitation_medicine"
            },
            {
                "label_en": "Spinal cord injury medicine",
                "label_de": "Arzneimittel gegen Rückenmarksverletzungen",
                "label_nl": "Spinal cord injury medicine",
                "label_rs": "Медицина травм спинного мозга",
                "label_sp": "Spinal cord injury medicine",
                "label_pt": "Spinal cord injury medicine",
                "label_sw": "Dawa ya kuumia ya uti wa mgongo",
                "label_ch": "脊髓损伤医学",
                "label_fr": "Médecine des lésions de la moelle épinière",
                "value": "Spinal_cord_injury_medicine"
            },
            {
                "label_en": "Sports medicine",
                "label_de": "Sportmedizin",
                "label_nl": "Sports medicine",
                "label_rs": "Спортивная медицина",
                "label_sp": "Sports medicine",
                "label_pt": "Sports medicine",
                "label_sw": "Dawa ya michezo",
                "label_ch": "运动医学",
                "label_fr": "Médecine du sport",
                "value": "Sports_medicine"
            },
            {
                "label_en": "Aerospace medicine",
                "label_de": "Luft-und_Raumfahrtmedizin",
                "label_nl": "Aerospace medicine",
                "label_rs": "Авиационно-космическая медицина",
                "label_sp": "Aerospace medicine",
                "label_pt": "Aerospace medicine",
                "label_sw": "Dawa ya kutumia angani",
                "label_ch": "航空医学",
                "label_fr": "Médecine aérospatiale",
                "value": "Aerospace_medicine"
            },
            {
                "label_en": "Medical toxicology",
                "label_de": "Medizinische Toxikologie",
                "label_nl": "Medical toxicology",
                "label_rs": "Медицинская токсикология",
                "label_sp": "Medical toxicology",
                "label_pt": "Medical toxicology",
                "label_sw": "Matibabu ya sumu",
                "label_ch": "医学毒理学",
                "label_fr": "Toxicologie médicale",
                "value": "Medical_toxicology"
            },
            {
                "label_en": "Occupational medicine",
                "label_de": "Arbeitsmedizin",
                "label_nl": "Occupational medicine",
                "label_rs": "Медицина труда",
                "label_sp": "Occupational medicine",
                "label_pt": "Occupational medicine",
                "label_sw": "Dawa ya kazini",
                "label_ch": "职业医学",
                "label_fr": "Médecine du travail",
                "value": "Occupational_medicine"
            },
            {
                "label_en": "Public health medicine",
                "label_de": "Public health medicine",
                "label_nl": "Public health medicine",
                "label_rs": "Медицина общественного здравоохранения",
                "label_sp": "Public health medicine",
                "label_pt": "Public health medicine",
                "label_sw": "Dawa ya afya ya umma",
                "label_ch": "公共卫生医学",
                "label_fr": "Médecine de santé publique",
                "value": "Public_health_medicine"
            },
            {
                "label_en": "Administrative psychiatry",
                "label_de": "Verwaltungspsychiatrie",
                "label_nl": "Administrative psychiatry",
                "label_rs": "Административная психиатрия",
                "label_sp": "Administrative psychiatry",
                "label_pt": "Administrative psychiatry",
                "label_sw": "Saikolojia ya kiutawala",
                "label_ch": "行政精神病学",
                "label_fr": "Psychiatrie administrative",
                "value": "Administrative_psychiatry"
            },
            {
                "label_en": "Child and adolescent psychiatry",
                "label_de": "Kinder-und Jugendpsychiatrie",
                "label_nl": "Child and adolescent psychiatry",
                "label_rs": "Детская и подростковая психиатрия",
                "label_sp": "Child and adolescent psychiatry",
                "label_pt": "Child and adolescent psychiatry",
                "label_sw": "Saikolojia ya watoto na vijana",
                "label_ch": "儿童和青少年精神病学",
                "label_fr": "Psychiatrie de l'enfant et de l'adolescent",
                "value": "Child_and_adolescent_psychiatry"
            },
            {
                "label_en": "Community psychiatry",
                "label_de": "Gemeinschaftspsychiatrie",
                "label_nl": "Community psychiatry",
                "label_rs": "Общественная психиатрия",
                "label_sp": "Community psychiatry",
                "label_pt": "Community psychiatry",
                "label_sw": "Saikolojia ya jamii",
                "label_ch": "社区精神病学",
                "label_fr": "Psychiatrie communautaire",
                "value": "Community_psychiatry"
            },
            {
                "label_en": "Consultation/liaison psychiatry",
                "label_de": "Konsultation / Verbindungspsychiatrie",
                "label_nl": "Consultation/liaison psychiatry",
                "label_rs": "Консультативная психиатрия",
                "label_sp": "Consultation/liaison psychiatry",
                "label_pt": "Consultation/liaison psychiatry",
                "label_sw": "Mashauriano / uhusiano wa kisiakolojia",
                "label_ch": "咨询/联络精神病学",
                "label_fr": "Psychiatrie de consultation/liaison",
                "value": "Consultation/liaison_psychiatry"
            },
            {
                "label_en": "Emergency psychiatry",
                "label_de": "Notfallpsychiatrie",
                "label_nl": "Emergency psychiatry",
                "label_rs": "Неотложная психиатрия",
                "label_sp": "Emergency psychiatry",
                "label_pt": "Emergency psychiatry",
                "label_sw": "Saikolojia ya dharura",
                "label_ch": "紧急精神病学",
                "label_fr": "Psychiatrie d'urgence",
                "value": "Emergency_psychiatry"
            },
            {
                "label_en": "Forensic psychiatry",
                "label_de": "Forensische Psychiatrie",
                "label_nl": "Forensic psychiatry",
                "label_rs": "Судебная психиатрия",
                "label_sp": "Forensic psychiatry",
                "label_pt": "Forensic psychiatry",
                "label_sw": "Saikolojia ya kiuchunguzi",
                "label_ch": "法医精神病学",
                "label_fr": "Psychiatrie légale",
                "value": "Forensic_psychiatry"
            },
            {
                "label_en": "Geriatric psychiatry",
                "label_de": "Geriatrische Psychiatrie",
                "label_nl": "Geriatric psychiatry",
                "label_rs": "Гериатрическая психиатрия",
                "label_sp": "Geriatric psychiatry",
                "label_pt": "Geriatric psychiatry",
                "label_sw": "Saikolojia ya kizazi",
                "label_ch": "老年精神病学",
                "label_fr": "Geriatric psychiatry",
                "value": "Geriatric_psychiatry"
            },
            {
                "label_en": "Mental retardation psychiatry",
                "label_de": "Psychiatrie für geistige Behinderung",
                "label_nl": "Mental retardation psychiatry",
                "label_rs": "Психиатрия умственной отсталости",
                "label_sp": "Mental retardation psychiatry",
                "label_pt": "Mental retardation psychiatry",
                "label_sw": "Saikolojia ya kudhoofika kwa akili",
                "label_ch": "精神发育迟缓精神病学",
                "label_fr": "Psychiatrie du retard mental",
                "value": "Mental_retardation_psychiatry"
            },
            {
                "label_en": "Military psychiatry",
                "label_de": "Militärpsychiatrie",
                "label_nl": "Military psychiatry",
                "label_rs": "Военная психиатрия",
                "label_sp": "Military psychiatry",
                "label_pt": "Military psychiatry",
                "label_sw": "Saikolojia ya jeshi",
                "label_ch": "军事精神病学",
                "label_fr": "Psychiatrie militaire",
                "value": "Military_psychiatry"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Psychiatric research",
                "label_de": "Psychiatrische_Forschung",
                "label_nl": "Psychiatric research",
                "label_rs": "Психиатрические исследования",
                "label_sp": "Psychiatric research",
                "label_pt": "Psychiatric research",
                "label_sw": "Utafiti wa kisiakolojia",
                "label_ch": "精神病学研究",
                "label_fr": "Recherche en psychiatrie",
                "value": "Psychiatric_research"
            },
            {
                "label_en": "Psychosomatic medicine",
                "label_de": "Psychosomatische Medizin",
                "label_nl": "Psychosomatic medicine",
                "label_rs": "Психосоматическая медицина",
                "label_sp": "Psychosomatic medicine",
                "label_pt": "Psychosomatic medicine",
                "label_sw": "Dawa ya kisaikolojia",
                "label_ch": "心身医学",
                "label_fr": "Médecine psychosomatique",
                "value": "Psychosomatic_medicine"
            },
            {
                "label_en": "Hospice and palliative medicine",
                "label_de": "Hospiz und Palliativmedizin",
                "label_nl": "Hospice and palliative medicine",
                "label_rs": "Хоспис и паллиативная медицина",
                "label_sp": "Hospice and palliative medicine",
                "label_pt": "Hospice and palliative medicine",
                "label_sw": "Hospitali na dawa ya kutuliza",
                "label_ch": "临终关怀和姑息药",
                "label_fr": "Hospice et médecine palliative",
                "value": "Hospice_and_palliative_medicine"
            },
            {
                "label_en": "Pain medicine",
                "label_de": "Schmerzmittel",
                "label_nl": "Pain medicine",
                "label_rs": "Медицина болевых синдромов",
                "label_sp": "Pain medicine",
                "label_pt": "Pain medicine",
                "label_sw": "Dawa ya maumivu",
                "label_ch": "止痛药",
                "label_fr": "Médicaments antidouleur",
                "value": "Pain_medicine"
            },
            {
                "label_en": "Colon and rectal surgery",
                "label_de": "Colon and rectal surgery",
                "label_nl": "Colon and rectal surgery",
                "label_rs": "Хирургия толстой и прямой кишки",
                "label_sp": "Colon and rectal surgery",
                "label_pt": "Colon and rectal surgery",
                "label_sw": "Oparesheni wa Colon na rectal",
                "label_ch": "结肠和直肠手术",
                "label_fr": "Chirurgie du côlon et du rectum",
                "value": "Colon_and_rectal_surgery"
            },
            {
                "label_en": "Surgical critical care",
                "label_de": "Chirurgische Intensivpflege",
                "label_nl": "Surgical critical care",
                "label_rs": "Хирургическая реанимация",
                "label_sp": "Surgical critical care",
                "label_pt": "Surgical critical care",
                "label_sw": "Huduma muhimu ya Oparesheni",
                "label_ch": "外科重症监护",
                "label_fr": "Soins intensifs chirurgicaux",
                "value": "Surgical_critical_care"
            },
            {
                "label_en": "Gynecologic oncology",
                "label_de": "Gynäkologische Onkologie",
                "label_nl": "Gynecologic oncology",
                "label_rs": "Гинекологическая онкология",
                "label_sp": "Gynecologic oncology",
                "label_pt": "Gynecologic oncology",
                "label_sw": "Oncolojia ya Gynecologic",
                "label_ch": "妇科肿瘤",
                "label_fr": "Oncologie gynécologique",
                "value": "Gynecologic_oncology"
            },
            {
                "label_en": "Plastic surgery",
                "label_de": "Plastische Chirurgie",
                "label_nl": "Plastic surgery",
                "label_rs": "Пластическая хирургия",
                "label_sp": "Plastic surgery",
                "label_pt": "Plastic surgery",
                "label_sw": "Oparesheni wa kiplastiki",
                "label_ch": "整形外科",
                "label_fr": "Chirurgie plastique",
                "value": "Plastic_surgery"
            },
            {
                "label_en": "Craniofacial surgery",
                "label_de": "Kraniofaziale Chirurgie",
                "label_nl": "Craniofacial surgery",
                "label_rs": "Черепно-лицевая хирургия",
                "label_sp": "Craniofacial surgery",
                "label_pt": "Craniofacial surgery",
                "label_sw": "Craniofacial surgery",
                "label_ch": "颅面外科",
                "label_fr": "Chirurgie cranio-faciale",
                "value": "Craniofacial_surgery"
            },
            {
                "label_en": "Hand surgery",
                "label_de": "Handchirurgie",
                "label_nl": "Hand surgery",
                "label_rs": "Хирургия кисти",
                "label_sp": "Hand surgery",
                "label_pt": "Hand surgery",
                "label_sw": "Oparesheni wa mkono",
                "label_ch": "手部手术",
                "label_fr": "Chirurgie de la main",
                "value": "Hand_surgery"
            },
            {
                "label_en": "Neurological surgery",
                "label_de": "Neurologische Chirurgie",
                "label_nl": "Neurological surgery",
                "label_rs": "Неврологическая хирургия",
                "label_sp": "Neurological surgery",
                "label_pt": "Neurological surgery",
                "label_sw": "Oparesheni wa neva",
                "label_ch": "神经外科手术",
                "label_fr": "Chirurgie neurologique",
                "value": "Neurological_surgery"
            },
            {
                "label_en": "Endovascular surgical neuroradiology",
                "label_de": "Endovaskuläre chirurgische Neuroradiologie",
                "label_nl": "Endovascular surgical neuroradiology",
                "label_rs": "Эндоваскулярная хирургическая нейрорадиология",
                "label_sp": "Endovascular surgical neuroradiology",
                "label_pt": "Endovascular surgical neuroradiology",
                "label_sw": "Neuroradiolojia ya upasuaji wa mishipa",
                "label_ch": "血管内手术神经放射学",
                "label_fr": "Neuroradiologie chirurgicale endovasculaire",
                "value": "Endovascular_surgical_neuroradiology"
            },
            {
                "label_en": "Ophthalmic surgery",
                "label_de": "Augenchirurgie",
                "label_nl": "Ophthalmic surgery",
                "label_rs": "Офтальмологическая хирургия",
                "label_sp": "Ophthalmic surgery",
                "label_pt": "Ophthalmic surgery",
                "label_sw": "Oparesheni ya macho",
                "label_ch": "眼科手术",
                "label_fr": "Chirurgie ophtalmique",
                "value": "Ophthalmic_surgery"
            },
            {
                "label_en": "Oral and maxillofacial surgery",
                "label_de": "Mund-und_Kieferchirurgie",
                "label_nl": "Oral and maxillofacial surgery",
                "label_rs": "Челюстно-лицевая хирургия",
                "label_sp": "Oral and maxillofacial surgery",
                "label_pt": "Oral and maxillofacial surgery",
                "label_sw": "Oral and maxillofacial surgery",
                "label_ch": "Oral and maxillofacial surgery",
                "label_fr": "Chirurgie buccale et maxillo-faciale",
                "value": "Oral_and_maxillofacial_surgery"
            },
            {
                "label_en": "HEAD AND NECK SURGERY",
                "label_de": "KOPF-UND HALSCHIRURGIE",
                "label_nl": "HEAD AND NECK SURGERY",
                "label_rs": "Хирургия головы и шеи",
                "label_sp": "HEAD AND NECK SURGERY",
                "label_pt": "HEAD AND NECK SURGERY",
                "label_sw": "OPARESHENI WA KICHWA NA SHINGO",
                "label_ch": "头颈部手术",
                "label_fr": "CHIRURGIE DE LA TÊTE ET DU COU",
                "value": "HEAD_AND_NECK_SURGERY"
            },
            {
                "label_en": "Orthopaedic surgery",
                "label_de": "Orthopädische Chirurgie",
                "label_nl": "Orthopaedic surgery",
                "label_rs": "Ортопедическая хирургия",
                "label_sp": "Orthopaedic surgery",
                "label_pt": "Orthopaedic surgery",
                "label_sw": "Oparesheni wa mifupa",
                "label_ch": "骨科手术",
                "label_fr": "Chirurgie orthopédique",
                "value": "Orthopaedic_surgery"
            },
            {
                "label_en": "Adult reconstructive orthopaedics",
                "label_de": "Rekonstruktive Orthopädie für Erwachsene",
                "label_nl": "Adult reconstructive orthopaedics",
                "label_rs": "Реконструктивная ортопедия",
                "label_sp": "Adult reconstructive orthopaedics",
                "label_pt": "Adult reconstructive orthopaedics",
                "label_sw": "Ujenzi ya mifupa ya watu wazima",
                "label_ch": "成人重建骨科",
                "label_fr": "Orthopédie reconstructive pour adultes",
                "value": "Adult_reconstructive_orthopaedics"
            },
            {
                "label_en": "Foot and ankle orthopaedics",
                "label_de": "Foot and ankle orthopaedics",
                "label_nl": "Foot and ankle orthopaedics",
                "label_rs": "Ортопедия стопы и голеностопного сустава",
                "label_sp": "Foot and ankle orthopaedics",
                "label_pt": "Foot and ankle orthopaedics",
                "label_sw": "Hali ya mfupa wa mguu na kifundo",
                "label_ch": "足踝骨科",
                "label_fr": "Orthopédie du pied et de la cheville",
                "value": "Foot_and_ankle_orthopaedics"
            },
            {
                "label_en": "Musculoskeletal oncology",
                "label_de": "Musculoskeletal oncology",
                "label_nl": "Musculoskeletal oncology",
                "label_rs": "Онкология опорно-двигательного аппарата",
                "label_sp": "Musculoskeletal oncology",
                "label_pt": "Musculoskeletal oncology",
                "label_sw": "Onkolojia ya mifupa",
                "label_ch": "肌肉骨骼肿瘤学",
                "label_fr": "Oncologie musculo-squelettique",
                "value": "Musculoskeletal_oncology"
            },
            {
                "label_en": "Orthopaedic sports medicine",
                "label_de": "Orthopaedic sports medicine",
                "label_nl": "Orthopaedic sports medicine",
                "label_rs": "Ортопедическая спортивная медицина",
                "label_sp": "Orthopaedic sports medicine",
                "label_pt": "Orthopaedic sports medicine",
                "label_sw": "Dawa ya michezo ya mifupa",
                "label_ch": "骨科运动医学",
                "label_fr": "Médecine sportive orthopédique",
                "value": "Orthopaedic_sports_medicine"
            },
            {
                "label_en": "Orthopaedic surgery of the spine",
                "label_de": "Onkologie des Bewegungsapparates",
                "label_nl": "Orthopaedic surgery of the spine",
                "label_rs": "Ортопедическая хирургия позвоночника",
                "label_sp": "Orthopaedic surgery of the spine",
                "label_pt": "Orthopaedic surgery of the spine",
                "label_sw": "Upasuaji wa mifupa ya mgongo",
                "label_ch": "脊柱骨科手术",
                "label_fr": "Chirurgie orthopédique de la colonne vertébrale",
                "value": "Orthopaedic_surgery_of_the_spine"
            },
            {
                "label_en": "Orthopaedic trauma",
                "label_de": "Orthopädische Sportmedizin",
                "label_nl": "Orthopaedic trauma",
                "label_rs": "Ортопедическая травма",
                "label_sp": "Orthopaedic trauma",
                "label_pt": "Orthopaedic trauma",
                "label_sw": "kiwewe cha mifupa",
                "label_ch": "骨科创伤",
                "label_fr": "Traumatisme orthopédique",
                "value": "Orthopaedic_trauma"
            },
            {
                "label_en": "Pediatric orthopaedics",
                "label_de": "Orthopädische Chirurgie der Wirbelsäule",
                "label_nl": "Pediatric orthopaedics",
                "label_rs": "Детская ортопедия",
                "label_sp": "Pediatric orthopaedics",
                "label_pt": "Pediatric orthopaedics",
                "label_sw": "Mifupa ya watoto",
                "label_ch": "小儿骨科",
                "label_fr": "Orthopédie pédiatrique",
                "value": "Pediatric_orthopaedics"
            },
            {
                "label_en": "Otolaryngology",
                "label_de": "Orthopädisches Trauma",
                "label_nl": "KNO-geneeskunde",
                "label_rs": "Отоларингология",
                "label_sp": "Otorrinolaringología",
                "label_pt": "Otorrinolaringologia",
                "label_sw": "Otolaryngolojia",
                "label_ch": "耳鼻喉科",
                "label_fr": "Otolaryngologie",
                "value": "Otolaryngology"
            },
            {
                "label_en": "Pediatric otolaryngology",
                "label_de": "Kinderorthopädie",
                "label_nl": "Pediatric otolaryngology",
                "label_rs": "Детская отоларингология",
                "label_sp": "Pediatric otolaryngology",
                "label_pt": "Pediatric otolaryngology",
                "label_sw": "Otolaryngolojia ya watoto",
                "label_ch": "小儿耳鼻喉科",
                "label_fr": "Otolaryngologie pédiatrique",
                "value": "Pediatric_otolaryngology"
            },
            {
                "label_en": "Otology neurotology",
                "label_de": "Otologie Neurotologie",
                "label_nl": "Otology neurotology",
                "label_rs": "Отология и нейротология",
                "label_sp": "Otology neurotology",
                "label_pt": "Otology neurotology",
                "label_sw": "Neurolojia ya Otolojia",
                "label_ch": "耳科神经学",
                "label_fr": "Otologie neurotologie",
                "value": "Otology_neurotology"
            },
            {
                "label_en": "Pediatric surgery",
                "label_de": "Kinderchirurgie",
                "label_nl": "Pediatric surgery",
                "label_rs": "Детская хирургия",
                "label_sp": "Pediatric surgery",
                "label_pt": "Pediatric surgery",
                "label_sw": "Oparesheni ya wa watoto",
                "label_ch": "小儿外科",
                "label_fr": "Chirurgie pédiatrique",
                "value": "Pediatric_surgery"
            },
            {
                "label_en": "Neonatal",
                "label_de": "Neugeborene",
                "label_nl": "Neonataal",
                "label_rs": "Неонатальный",
                "label_sp": "Neonatal",
                "label_pt": "Neonatal",
                "label_sw": "Mtoto mchanga",
                "label_ch": "新生儿",
                "label_fr": "Néonatal",
                "value": "Neonatal"
            },
            {
                "label_en": "Prenatal",
                "label_de": "Vorgeburtlich",
                "label_nl": "Prenataal",
                "label_rs": "Пренатальный",
                "label_sp": "Prenatal",
                "label_pt": "Pré-natal",
                "label_sw": "kabla ya kuzaa",
                "label_ch": "产前",
                "label_fr": "Prénatal",
                "value": "Prenatal"
            },
            {
                "label_en": "Trauma",
                "label_de": "Trauma",
                "label_nl": "Trauma",
                "label_rs": "Травма",
                "label_sp": "Trauma",
                "label_pt": "Trauma",
                "label_sw": "Kiwewe",
                "label_ch": "创伤",
                "label_fr": "Traumatisme",
                "value": "Trauma"
            },
            {
                "label_en": "Pediatric oncology",
                "label_de": "Pädiatrische Onkologie",
                "label_nl": "Pediatric oncology",
                "label_rs": "Детская онкология",
                "label_sp": "Pediatric oncology",
                "label_pt": "Pediatric oncology",
                "label_sw": "Oncolojia ya watoto",
                "label_ch": "小儿肿瘤",
                "label_fr": "Oncologie pédiatrique",
                "value": "Pediatric_oncology"
            },
            {
                "label_en": "Thoracic Surgery",
                "label_de": "Brustchirurgie",
                "label_nl": "Thoracic Surgery",
                "label_rs": "Торакальная хирургия",
                "label_sp": "Thoracic Surgery",
                "label_pt": "Thoracic Surgery",
                "label_sw": "Oparesheni ya kifua",
                "label_ch": "胸外科",
                "label_fr": "Chirurgie thoracique",
                "value": "Thoracic_Surgery"
            },
            {
                "label_en": "Congenital cardiac surgery",
                "label_de": "Angeborene Herzchirurgie",
                "label_nl": "Congenital cardiac surgery",
                "label_rs": "Кардиохирургия наследственных заболеваний",
                "label_sp": "Congenital cardiac surgery",
                "label_pt": "Congenital cardiac surgery",
                "label_sw": "Oparesheni wa moyo wa kuzaliwa",
                "label_ch": "先天性心脏手术",
                "label_fr": "Chirurgie cardiaque congénitale",
                "value": "Congenital_cardiac_surgery"
            },
            {
                "label_en": "Thoracic surgery-integrated",
                "label_de": "Integrierte Thoraxchirurgie",
                "label_nl": "Thoracic surgery-integrated",
                "label_rs": "Торакальная хирургия: комплексная",
                "label_sp": "Thoracic surgery-integrated",
                "label_pt": "Thoracic surgery-integrated",
                "label_sw": "Oparesheni wa kifua jumuishi",
                "label_ch": "胸外科-集成",
                "label_fr": "Chirurgie thoracique intégrée",
                "value": "Thoracic_surgery-integrated"
            },
            {
                "label_en": "Vascular surgery",
                "label_de": "Gefäßchirurgie",
                "label_nl": "Vascular surgery",
                "label_rs": "Сосудистая хирургия",
                "label_sp": "Vascular surgery",
                "label_pt": "Vascular surgery",
                "label_sw": "Oparesheni wa mishipa",
                "label_ch": "血管手术",
                "label_fr": "Chirurgie vasculaire",
                "value": "Vascular_surgery"
            },
            {
                "label_en": "Pediatric urology",
                "label_de": "Kinderurologie",
                "label_nl": "Pediatric urology",
                "label_rs": "Детская урология",
                "label_sp": "Pediatric urology",
                "label_pt": "Pediatric urology",
                "label_sw": "Urolojia ya watoto",
                "label_ch": "儿科泌尿科",
                "label_fr": "Urologie pédiatrique",
                "value": "Pediatric_urology"
            },
            {
                "label_en": "Urologic oncology",
                "label_de": "Urologische Onkologie",
                "label_nl": "Urologic oncology",
                "label_rs": "Урологическая онкология",
                "label_sp": "Urologic oncology",
                "label_pt": "Urologic oncology",
                "label_sw": "Oncolojia ya Urolojia",
                "label_ch": "泌尿肿瘤",
                "label_fr": "Oncologie urologique",
                "value": "Urologic_oncology"
            },
            {
                "label_en": "Renal transplant",
                "label_de": "Nierentransplantation",
                "label_nl": "Renal transplant",
                "label_rs": "Трансплантация почки",
                "label_sp": "Renal transplant",
                "label_pt": "Renal transplant",
                "label_sw": "Kupandikiza figo",
                "label_ch": "肾移植",
                "label_fr": "Transplantation rénale",
                "value": "Renal_transplant"
            },
            {
                "label_en": "Male infertility",
                "label_de": "Männliche Unfruchtbarkeit",
                "label_nl": "Male infertility",
                "label_rs": "Мужское бесплодие",
                "label_sp": "Male infertility",
                "label_pt": "Male infertility",
                "label_sw": "Ugumba wa kiume",
                "label_ch": "男性不孕不育",
                "label_fr": "Infertilité masculine",
                "value": "Male_infertility"
            },
            {
                "label_en": "Calculi",
                "label_de": "Kalküle",
                "label_nl": "Calculi",
                "label_rs": "Камни в организмах",
                "label_sp": "Cálculos",
                "label_pt": "Cálculos",
                "label_sw": "Calculi",
                "label_ch": "结石",
                "label_fr": "Calculs",
                "value": "Calculi"
            },
            {
                "label_en": "Female urology",
                "label_de": "Weibliche Urologie",
                "label_nl": "Female urology",
                "label_rs": "Женская урология",
                "label_sp": "Female urology",
                "label_pt": "Female urology",
                "label_sw": "Urolojia ya kike",
                "label_ch": "女性泌尿科",
                "label_fr": "Urologie féminine",
                "value": "Female_urology"
            },
            {
                "label_en": "Neurourology",
                "label_de": "Neurourologie",
                "label_nl": "Neurourologie",
                "label_rs": "Нейроурология",
                "label_sp": "Neurourología",
                "label_pt": "Neurourologia",
                "label_sw": "Neurourolojia",
                "label_ch": "神经泌尿学",
                "label_fr": "Neurourologie",
                "value": "Neurourology"
            }
        ]
    }
exports.subspeciality = subspeciality;